### ISSUE TITLE
Align this container to center.

### ISSUE THREAD

**Issue by ashimthapa12** [sauravkunwar/Portfolio-Management#8]
<img width="1341" alt="Screen Shot 2021-05-15 at 5 21 01 PM" src="https://user-images.githubusercontent.com/82638770/118359165-f3d33780-b5a1-11eb-9f2f-b2628d17b67e.png">

**Comment by sauravkunwar** [comment]
![2021-05-15 (23)](https://user-images.githubusercontent.com/82306833/118359190-12393300-b5a2-11eb-8a6b-5153b3e829cf.png)

**The issue has been fixed and the enhancement has been made.**
