### ISSUE TITLE
Maintain these data and information in tabular form.

### ISSUE THREAD

**Issue by RajatBudhathoki1234** [sauravkunwar/Portfolio-Management#9]
![2021-05-15 (1)](https://user-images.githubusercontent.com/82403608/118359010-1749b280-b5a1-11eb-9523-0b32390f0522.png)
![2021-05-15](https://user-images.githubusercontent.com/82403608/118359012-19137600-b5a1-11eb-8a8e-02e524e6b25c.png)

**Put these data in tabular form with nice font.**

**Comment by sauravkunwar** [comment]
![2021-05-15 (28)](https://user-images.githubusercontent.com/82306833/118359246-5a585580-b5a2-11eb-9072-cd284750bcb3.png)
![2021-05-15 (27)](https://user-images.githubusercontent.com/82306833/118359249-5d534600-b5a2-11eb-9822-5dcb024fb6c3.png)

**The issue has been resolved and enhancement has been done.**
